### PR TITLE
Add py.typed

### PR DESCRIPTION
**Pull request by AbdealiLoKo**
Adding py.typed file as per pep-0561 so that users of the package are
able to use the typing information in the package

### CODE REVIEW

**Comment by AbdealiLoKo** [comment]
@sloria / @jmcarp - I was using typing for my application and was about to write stubs for this package.
But then I realized that typing is already being used here.

But it was not being taken up as no py.typed was added. Let me know if you think the types are stable enough to be used by application writers ?

**Comment by AbdealiLoKo** [comment]
Quick bump on this - if all looks ok. I can merge

**Comment by bruceadams** [comment]
Adding `py.typed` into my installed `marshmallow_sqlalchemy` (yes, this is a nasty hack on my part) allows `mypy` to correctly type check my code. I would love to see this merged in so my team can get type checking without hack-job workarounds.

**Comment by sloria** [comment]
Sorry for the delay on this.

@AbdealiJK i think this just needs this line? https://github.com/marshmallow-code/marshmallow/blob/65860eb91a171a121ab20220f09fa7dfb462cc12/setup.py#L59

**Comment by sloria** [comment]
oh also https://github.com/marshmallow-code/marshmallow/blob/dev/MANIFEST.in#L3

**Pull request closed without merging**
