### PR TITLE
Add postgresl.OID data type to SQLA_TYPE_MAPPING

### PR DESCRIPTION
**Pull request by petrus-v**

### CODE REVIEW

**Comment by petrus-v** [comment]
This is my first PR on this project, let me know if you have any requirements or guide lines to follow, I was wondering about the release process while filling the changelog !

(I'm reading https://marshmallow-sqlalchemy.readthedocs.io/en/latest/contributing.html... sorry about the noise)

**Comment by sloria** [comment]
Looks good, thanks! Can you also add yourself to AUTHORS.rst please?

**Comment by sloria** [comment]
Actually, went ahead and added you. =)

**Comment by petrus-v** [comment]
Great ! thanks a lot, (I guess we are not working on the same timezone :) ) !

**Pull request merged**
