### PR TITLE
Added money type to SQLA_TYPE_MAPPING

### PR DESCRIPTION
**Pull request by heckad**

### CODE REVIEW

**Comment by heckad** [comment]
Why py27-lowest don't have MONEY? It's correct?

**Comment by sloria** [comment]
It's probably not a py2-specific issue. Looks like our lowest supported SQLAlchemy version (0.9.7) doesn't support `MONEY`. I'm up for bumping up the minimum version; could you find which SQLA version adds MONEY?

**Comment by AbdealiLoKo** [comment]
May be better to add a check and add this field only if the sqla version is > some value rather than bumping it up

**Comment by sloria** [comment]
I'm fine with either. Looks like it was added in 1.2, which is ~1.5 years old at this point.

**Comment by heckad** [comment]
So what are we doing? We update the version or we write factory?

**Comment by sloria** [comment]
Well, we're already doing 

```python
    if hasattr(sa, "JSON"):
        SQLA_TYPE_MAPPING[sa.JSON] = fields.Raw
```

so we could do something similar

```python
    if hasattr(postgres, "MONEY"):
        SQLA_TYPE_MAPPING[postgres.MONEY] = fields.Decimal
```

**Comment by heckad** [comment]
Done

**Comment by heckad** [comment]
When it will be merged?

**Comment by sloria** [comment]
Will probably release this over the weekend.

**Comment by heckad** [comment]
Thanks!

**Comment by sloria** [comment]
This is released in 0.17.0

**Pull request merged**
