### PR TITLE
fields: Add RelatedList to handle attribute correctly

### PR DESCRIPTION
**Pull request by AbdealiLoKo**
Fixes https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/121

### CODE REVIEW

**Comment by AbdealiLoKo** [comment]
Travis failure seems to be unrelated to this patch

**Comment by sloria** [comment]
Thanks @AbdealiJK . I'll try to take a look at this when I get some time over the next few days

**Comment by AbdealiLoKo** [comment]
@sloria any thoughts on this ? I currently have a fork Im maintaining for this fix internally but would prefer solving upstream so I do not need to have a fork :)

**Review by sloria — APPROVED** [review]

**Comment by sloria** [comment]
Apologies for the delay. Behavior looks good. Good to merge!

**Comment by sloria** [comment]
By the way, I'm starting to use something along the lines of the [Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html). Basically, if you get a PR merged in, you get an invite to have commit access.

No pressure to do any more work than you already have. Just want to open the door to further collaboration. =)

**Pull request merged**
